In [31]:
import pandas as pd

In [32]:
import sqlite3
import pandas as pd
conn = sqlite3.connect('/Users/rodriguesmunguambe/Documents/kairos-portal/backend/kairos_banking.db')

In [33]:
cursor = conn.cursor()
cursor.execute("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name")
print(cursor.fetchall())

[('accounts',), ('aml_alerts',), ('banks',), ('branches',), ('cards',), ('collateral',), ('corporate_account_signatories',), ('countries',), ('currencies',), ('customer_addresses',), ('customers',), ('fx_rates',), ('loans',), ('sanctions_list',), ('signatories',), ('transaction_channels',), ('transaction_types',), ('transactions',)]

In [34]:
# See all EFT us-on-us transactions
df_eft_ut = pd.read_sql("SELECT * FROM v_eft_us_on_them order by transaction_date desc LIMIT 10", conn)
df_eft_ut

,transaction_id,transaction_reference,transaction_date,amount,currency_code,local_currency_amount,debit_credit_indicator,internal_account,internal_customer_name,internal_tax_number,external_account,external_customer_name,external_bank,remittance_information,suspicious_flag,structuring_flag
0,9936,EFT-UT-001936,2026-05-15 18:57:40,510485.39,MZN,510485.39,C,00830153251117,Moçambique Saúde e Farmácia S.A.,474678197,00100633791204,Grupo Muchanga Lda,Banco Comercial e de Investimentos,Transferência para Grupo Muchanga Lda,0,0
1,11366,EFT-UT-003366,2026-05-15 18:20:18,1533034.88,MZN,1533034.88,D,00830131343124,Grupo Cuvele S.A.,343519224,00700603940923,Munguambe & Machava S.A.,African Banking Corporation,Transferência para Munguambe & Machava,0,0
2,9613,EFT-UT-001613,2026-05-15 18:07:11,1440199.13,MZN,1440199.13,C,00830149324057,Machangana Tecnologia de Informação Lda,351918807,00200685315113,Bila & Cumbe S.A.,Millennium BIM,Transferência para Bila & Cumbe S.A.,0,0
3,10997,EFT-UT-002997,2026-05-15 17:58:43,468816.95,MZN,468816.95,D,00830182268569,Moçambique Transportes e Logística Lda,764367634,00900975746845,Moçambique Indústria Transformadora Lda,Moza Banco,Transferência para Moçambique Indústria,0,0
4,11960,EFT-UT-003960,2026-05-15 17:26:40,240754.73,MZN,240754.73,C,00830174313364,Muchanga Consultoria e Assessoria Lda,714205566,00100031510031,Machava & Nguenha S.A.,Banco Comercial e de Investimentos,Transferência para Machava & Nguenha S.,0,0
5,8353,EFT-UT-000353,2026-05-15 16:11:04,98010.05,MZN,98010.05,D,00830104003965,Tembe & Nhateve Lda,782356654,00900648339328,Moçambique Transportes e Logística Lda,Moza Banco,Transferência para Moçambique Transport,0,1
6,11947,EFT-UT-003947,2026-05-15 16:10:39,1443716.69,MZN,1443716.69,C,00830160033666,Uamusse Hotelaria e Turismo Lda,408706845,00400735877407,Moçambique Tecnologia de Informação Lda,Société Générale Mozambique,Transferência para Moçambique Tecnologi,1,0
7,10767,EFT-UT-002767,2026-05-15 15:28:56,808677.62,MZN,808677.62,D,00830189507892,Nhateve & Nhacuamba S.A.,949537284,00200708871383,Nhantumbo & Uamusse SARL,Millennium BIM,Transferência para Nhantumbo & Uamusse,0,0
8,10972,EFT-UT-002972,2026-05-15 14:57:08,1459469.12,MZN,1459469.12,D,00830180502337,Moçambique Tecnologia de Informação Lda,594320303,00400914235230,Grupo Mondlane S.A.,Société Générale Mozambique,Transferência para Grupo Mondlane S.A.,0,0
9,10915,EFT-UT-002915,2026-05-15 14:19:28,2675627.77,MZN,2675627.77,C,00830119265560,Chemane & Macamo S.A.,917380854,00700487403099,Grupo Pateguana S.A.,African Banking Corporation,Transferência para Grupo Pateguana S.A.,0,0

In [35]:
pd.read_sql("""select * from customers limit 10 """, conn)

,customer_id,customer_type,customer_name,first_name,middle_name,last_name,gender,marital_status,date_of_birth,incorporation_date,...,onboarding_date,relationship_manager,risk_rating,aml_risk_score,pep_flag,sanctions_flag,deceased_flag,customer_status,created_at,updated_at
0,1,CORPORATE,Vilanculos Saúde e Farmácia Lda,None,None,None,None,None,None,2019-05-18,...,2015-08-17,Adriano Nhantumbo,MEDIUM,35.38,0,0,0,ACTIVE,2026-05-28 10:39:40,2026-05-28 10:39:40
1,2,CORPORATE,Moçambique Transportes e Logística S.A.,None,None,None,None,None,None,2014-05-10,...,2022-06-28,Beatriz Cumbe,LOW,85.05,0,0,0,ACTIVE,2026-05-28 10:39:40,2026-05-28 10:39:40
2,3,CORPORATE,Moçambique Serviços Financeiros S.A.,None,None,None,None,None,None,2001-01-26,...,2015-07-14,Sofia Machava,LOW,16.60,0,0,0,ACTIVE,2026-05-28 10:39:40,2026-05-28 10:39:40
3,4,CORPORATE,Nhacuamba & Cossa S.A.,None,None,None,None,None,None,2009-08-03,...,2018-04-03,Beatriz Mabunda,LOW,28.56,0,0,0,ACTIVE,2026-05-28 10:39:40,2026-05-28 10:39:40
4,5,CORPORATE,Grupo Nhavene Lda,None,None,None,None,None,None,2004-03-29,...,2021-05-01,Sofia Machava,LOW,24.16,0,0,0,ACTIVE,2026-05-28 10:39:40,2026-05-28 10:39:40
5,6,CORPORATE,Grupo Chemane Lda,None,None,None,None,None,None,2016-07-18,...,2023-09-17,Beatriz Mabunda,LOW,60.19,0,0,0,ACTIVE,2026-05-28 10:39:40,2026-05-28 10:39:40
6,7,CORPORATE,Grupo Cuvele S.A.,None,None,None,None,None,None,2011-07-29,...,2021-11-18,Adriano Nhantumbo,LOW,12.88,0,0,0,ACTIVE,2026-05-28 10:39:40,2026-05-28 10:39:40
7,8,CORPORATE,Macamo & Munguambe SARL,None,None,None,None,None,None,2014-02-06,...,2016-10-07,Luís Magaia,MEDIUM,34.32,0,0,0,ACTIVE,2026-05-28 10:39:40,2026-05-28 10:39:40
8,9,CORPORATE,Tembe & Nhateve Lda,None,None,None,None,None,None,2010-04-11,...,2022-03-19,Graça Vilanculos,MEDIUM,93.22,0,0,0,ACTIVE,2026-05-28 10:39:40,2026-05-28 10:39:40
9,10,CORPORATE,Grupo Nhacuamba S.A.,None,None,None,None,None,None,2002-08-22,...,2020-03-28,Beatriz Mabunda,LOW,66.81,0,0,0,ACTIVE,2026-05-28 10:39:40,2026-05-28 10:39:40

In [36]:
df_ctr = pd.read_sql("SELECT * FROM v_ctr", conn)
df_ctr

,transaction_id,transaction_reference,transaction_date,amount,local_currency_amount,debit_credit_indicator,internal_account,internal_customer_name,internal_tax_number,depositor_name,flow_type,remittance_information,suspicious_flag,structuring_flag,above_threshold
0,17004,CTR-000004,2026-01-26 18:56:17,904110.54,904110.54,C,00830101175211,Grupo Uamusse Lda,563654896,Cristina Muianga,ctr_deposit,Depósito em Numerário,0,0,1
1,17008,CTR-000008,2026-03-09 11:39:46,204490.37,204490.37,C,00830173209622,Guambe Importação e Exportação Lda,226298761,Beatriz Nguenha Sitoe,ctr_deposit,Depósito em Numerário,0,0,0
2,17009,CTR-000009,2026-04-27 10:34:22,207640.17,207640.17,C,00830177028590,Grupo Cossa S.A.,140292214,Pedro Muchanga,ctr_deposit,Depósito em Numerário,0,1,0
3,17010,CTR-000010,2026-05-15 07:37:17,221794.25,221794.25,C,00830152048700,Guambe Consultoria e Assessoria Lda,945558623,Fernando Magaia Cossa,ctr_deposit,Depósito em Numerário,0,0,0
4,17011,CTR-000011,2026-05-02 18:42:32,934194.98,934194.98,C,00830124893874,Guambe & Mabunda SARL,918075203,Rodrigo Muchanga Mabunda,ctr_deposit,Depósito em Numerário,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,21988,CTR-004988,2026-05-03 13:44:42,366927.14,366927.14,D,00830124491553,Machava & Muchanga Lda,797061750,Felício Guambe,ctr_withdrawal,Levantamento em Numerário,0,0,1
4996,21992,CTR-004992,2026-02-15 09:40:54,87304.91,87304.91,D,00830177893061,Machava Importação e Exportação Lda,516197459,Conceição Magaia Chibuto,ctr_withdrawal,Levantamento em Numerário,0,1,0
4997,21995,CTR-004995,2026-05-04 08:46:29,1434533.58,1434533.58,D,00830135460146,Grupo Pateguana Lda,913165162,Adriano Bila,ctr_withdrawal,Levantamento em Numerário,1,0,1
4998,21999,CTR-004999,2026-02-17 13:46:36,1032433.22,1032433.22,D,00830195922501,Grupo Nguenha S.A.,402515352,João Chemane Muchanga,ctr_withdrawal,Levantamento em Numerário,0,0,1
4999,22000,CTR-005000,2026-01-17 09:31:40,695899.10,695899.10,D,00830172170042,Nhantumbo & Muianga Lda,347782608,Domingos Guambe,ctr_withdrawal,Levantamento em Numerário,0,0,1

In [37]:
df_ctr['remittance_information'].value_counts()

remittance_information
Depósito em Numerário        2540
Levantamento em Numerário    2460
Name: count, dtype: int64

In [38]:
df_ift = pd.read_sql("SELECT * FROM v_ift LIMIT 10", conn)
df_ift

,transaction_id,transaction_reference,transaction_date,amount,currency_code,exchange_rate,local_currency_amount,debit_credit_indicator,internal_account,internal_customer_name,internal_tax_number,foreign_account,foreign_party_name,foreign_bank,foreign_swift,foreign_country,flow_type,remittance_information,suspicious_flag,sanctions_match_flag
0,12001,IFT-000001,2026-02-09 17:40:37,238521.01,EUR,69.20,1.650565e+07,C,00830189038140,Matsimbe & Munguambe S.A.,883131613,DE72115807956021806877,Muianga & Nhateve SARL,BNP Paribas,BNPAFRPP,FR,ift_incoming,International transfer — BNP Paribas,0,0
1,12002,IFT-000002,2026-01-08 17:48:12,9775763.84,USD,63.85,6.241825e+08,C,00830183277113,Moçambique Saúde e Farmácia S.A.,590886865,ZA97473228221950060428,Cossa Saúde e Farmácia Lda,Barclays Bank UK,BARCGB22,GB,ift_incoming,International transfer — Barclays Bank UK,0,0
2,12007,IFT-000007,2026-02-08 07:50:36,7377702.06,USD,63.85,4.710663e+08,C,00830142522436,Tembe & Mondlane Lda,839645609,PT74493829247904301917,Moçambique Construção Civil Lda,Deutsche Bank AG,DEUTDEDB,DE,ift_incoming,International transfer — Deutsche Bank AG,0,0
3,12008,IFT-000008,2026-05-07 17:36:02,4538462.34,EUR,69.20,3.140616e+08,C,00830156004109,Grupo Mabunda S.A.,997161052,ZA87830475153392202668,Grupo Zunguze Lda,Barclays Bank UK,BARCGB22,GB,ift_incoming,International transfer — Barclays Bank UK,0,0
4,12010,IFT-000010,2026-01-16 11:24:33,4017432.08,MZN,1.00,4.017432e+06,C,00830101346637,Moçambique Agricultura e Pecuária Lda,983602739,DE71337022655530245825,Bila Hotelaria e Turismo Lda,BNP Paribas,BNPAFRPP,FR,ift_incoming,International transfer — BNP Paribas,0,0
5,12011,IFT-000011,2026-03-01 14:38:53,3876188.01,MZN,1.00,3.876188e+06,C,00830169523802,Moçambique Indústria Transformadora Lda,995558095,ZA71330224103188715857,Cuvele & Matsimbe Lda,Deutsche Bank AG,DEUTDEDB,DE,ift_incoming,International transfer — Deutsche Bank AG,0,0
6,12012,IFT-000012,2026-03-08 17:16:58,9074418.87,ZAR,3.42,3.103451e+07,C,00830152048700,Guambe Consultoria e Assessoria Lda,945558623,ZA88365591618044369451,Moçambique Saúde e Farmácia S.A.,Standard Bank South Africa,SBZAZAJJ,ZA,ift_incoming,International transfer — Standard Bank South,0,0
7,12015,IFT-000015,2026-01-29 17:30:45,8785501.74,GBP,80.15,7.041580e+08,C,00830163200290,Moçambique Construção Civil Lda,274762758,GB18900634131397816552,Moçambique Indústria Transformadora S.A.,Banco Espirito Santo Angola,BESAANLA,AO,ift_incoming,International transfer — Banco Espirito Santo,0,0
8,12019,IFT-000019,2026-01-08 17:14:39,5983250.13,MZN,1.00,5.983250e+06,C,00830139132911,Moçambique Transportes e Logística Lda,491473739,GB26139332140984212697,Munguambe Consultoria e Assessoria Lda,HSBC Bank,HSBCGB2L,GB,ift_incoming,International transfer — HSBC Bank,1,0
9,12021,IFT-000021,2026-02-17 14:24:33,3886419.10,EUR,69.20,2.689402e+08,C,00830108363173,Grupo Munguambe Lda,361729428,DE50994339969409511307,Grupo Machava Lda,Absa Group Limited,ABSAZAJJ,ZA,ift_incoming,International transfer — Absa Group Limited,1,0

In [39]:
df_rates = pd.read_sql("SELECT * FROM countries LIMIT 10", conn)
df_rates

,country_code,country_name,iso3_code,risk_level,sanctions_flag,fatf_watchlist_flag
0,MZ,Mozambique,MOZ,LOW,0,0
1,ZA,South Africa,ZAF,LOW,0,0
2,PT,Portugal,PRT,LOW,0,0
3,GB,United Kingdom,GBR,LOW,0,0
4,DE,Germany,DEU,LOW,0,0
5,US,United States,USA,LOW,0,0
6,FR,France,FRA,LOW,0,0
7,AO,Angola,AGO,MEDIUM,0,0
8,TZ,Tanzania,TZA,LOW,0,0
9,ZW,Zimbabwe,ZWE,HIGH,0,1

In [42]:
# See all EFT us-on-us transactions
df_eft_ut = pd.read_sql("SELECT * FROM v_eft_us_on_us  where transaction_date between '2026-05-11' and '2026-05-18' and structuring_flag = 1", conn)
df_eft_ut

,transaction_id,transaction_reference,transaction_date,amount,currency_code,local_currency_amount,debit_credit_indicator,from_account,from_customer_name,from_customer_id,from_tax_number,to_account,to_customer_name,remittance_information,suspicious_flag,structuring_flag
0,11,EFT-UU-000011,2026-05-14 16:30:11,546397.49,MZN,546397.49,D,00830130260830,Bila Energia e Recursos Naturais Lda,159,384416251,00830174313364,Muchanga Consultoria e Assessoria Lda,Transferência interna ref.11,0,1
1,402,EFT-UU-000402,2026-05-11 15:48:53,407571.33,MZN,407571.33,D,00830101057839,Moçambique Agricultura e Pecuária S.A.,19,530487022,00830136061160,Bila Importação e Exportação Lda,Transferência interna ref.402,0,1
2,464,EFT-UU-000464,2026-05-11 09:08:58,292432.24,MZN,292432.24,D,00830148559573,Cumbe & Nhavene S.A.,37,371640873,00830176927735,Nhantumbo & Mondlane SARL,Transferência interna ref.464,0,1
3,482,EFT-UU-000482,2026-05-11 17:56:37,344722.55,MZN,344722.55,D,00830148559573,Cumbe & Nhavene S.A.,37,371640873,00830135460146,Grupo Pateguana Lda,Transferência interna ref.482,0,1
4,578,EFT-UU-000578,2026-05-13 16:43:21,582782.09,MZN,582782.09,D,00830118060910,Moçambique Transportes e Logística S.A.,111,657938168,00830104811773,Matsimbe & Magaia S.A.,Transferência interna ref.578,0,1
5,675,EFT-UU-000675,2026-05-12 17:13:20,332426.16,MZN,332426.16,D,00830177028590,Grupo Cossa S.A.,35,140292214,00830175587967,Pateguana & Muchanga Lda,Transferência interna ref.675,0,1
6,800,EFT-UU-000800,2026-05-15 12:16:19,470269.49,MZN,470269.49,D,00830108363173,Grupo Munguambe Lda,22,361729428,00830132477500,Moçambique Comércio Geral S.A.,Transferência interna ref.800,0,1
7,834,EFT-UU-000834,2026-05-14 08:54:13,252047.94,MZN,252047.94,D,00830103902796,Muianga & Mondlane S.A.,164,891882085,00830149062571,Tembe & Mondlane S.A.,Transferência interna ref.834,0,1
8,1213,EFT-UU-001213,2026-05-15 17:22:06,281738.71,MZN,281738.71,D,00830142522436,Tembe & Mondlane Lda,98,839645609,00830107467027,Moçambique Construção Civil Lda,Transferência interna ref.1213,0,1
9,1487,EFT-UU-001487,2026-05-11 09:50:54,403633.02,MZN,403633.02,D,00830160033666,Uamusse Hotelaria e Turismo Lda,191,408706845,00830163200290,Moçambique Construção Civil Lda,Transferência interna ref.1487,0,1
10,1614,EFT-UU-001614,2026-05-13 14:20:13,632318.94,MZN,632318.94,D,00830107499893,Grupo Muianga Lda,175,680664409,00830140712903,Grupo Uamusse S.A.,Transferência interna ref.1614,0,1
11,1678,EFT-UU-001678,2026-05-12 10:28:43,711765.52,MZN,711765.52,D,00830194737419,Muianga Telecomunicações Lda,161,193236414,00830173415218,Vilanculos Saúde e Farmácia Lda,Transferência interna ref.1678,0,1
12,1774,EFT-UU-001774,2026-05-14 12:10:53,706931.34,MZN,706931.34,D,00830161380512,Nhacuamba Telecomunicações Lda,129,305221144,00830183277113,Moçambique Saúde e Farmácia S.A.,Transferência interna ref.1774,0,1
13,1944,EFT-UU-001944,2026-05-14 13:21:21,225324.18,MZN,225324.18,D,00830152415780,Moçambique Serviços Financeiros S.A.,195,538500828,00830124893874,Guambe & Mabunda SARL,Transferência interna ref.1944,0,1
14,2066,EFT-UU-002066,2026-05-13 12:28:12,144351.34,MZN,144351.34,D,00830129586861,Machangana Indústria Transformadora Lda,185,737153642,00830152935704,Cossa Consultoria e Assessoria Lda,Transferência interna ref.2066,0,1
15,2100,EFT-UU-002100,2026-05-15 09:30:17,95477.57,MZN,95477.57,D,00830137523212,Zunguze Educação Lda,179,824122459,00830128055856,Uamusse & Chemane SARL,Transferência interna ref.2100,0,1
16,2501,EFT-UU-002501,2026-05-14 11:53:37,193617.30,MZN,193617.30,D,00830185206634,Grupo Cuvele S.A.,56,991025330,00830142942991,Machava Saúde e Farmácia Lda,Transferência interna ref.2501,0,1
17,3152,EFT-UU-003152,2026-05-11 13:22:38,317249.77,MZN,317249.77,D,00830104716096,Chaúque & Pateguana Lda,190,900059672,00830185206634,Grupo Cuvele S.A.,Transferência interna ref.3152,0,1
18,3349,EFT-UU-003349,2026-05-11 13:07:55,99118.42,MZN,99118.42,D,00830139396593,Moçambique Saúde e Farmácia Lda,142,190768948,00830160469115,Grupo Cossa S.A.,Transferência interna ref.3349,0,1
19,3713,EFT-UU-003713,2026-05-15 17:17:37,706697.58,MZN,706697.58,D,00830124893874,Guambe & Mabunda SARL,86,918075203,00830156004109,Grupo Mabunda S.A.,Transferência interna ref.3713,0,1
20,3880,EFT-UU-003880,2026-05-14 08:07:22,559691.13,MZN,559691.13,D,00830142274599,Chemane & Magaia S.A.,61,192389742,00830121728216,Moçambique Transportes e Logística Lda,Transferência interna ref.3880,0,1
21,3947,EFT-UU-003947,2026-05-13 10:44:52,82348.60,MZN,82348.60,D,00830165740754,Grupo Mondlane Lda,155,589824097,00830176927735,Nhantumbo & Mondlane SARL,Transferência interna ref.3947,0,1
22,3987,EFT-UU-003987,2026-05-11 08:06:16,683859.47,MZN,683859.47,D,00830180458079,Grupo Mondlane S.A.,108,381185433,00830107467027,Moçambique Construção Civil Lda,Transferência interna ref.3987,0,1
23,4019,EFT-UU-004019,2026-05-14 11:30:38,442573.87,MZN,442573.87,D,00830131562868,Moçambique Agricultura e Pecuária S.A.,154,149070149,00830139033189,Nhantumbo & Nhateve Lda,Transferência interna ref.4019,0,1
24,4088,EFT-UU-004088,2026-05-15 10:46:15,152954.24,MZN,152954.24,D,00830129052040,Cuvele Tecnologia de Informação Lda,34,512478084,00830137523212,Zunguze Educação Lda,Transferência interna ref.4088,0,1
25,4329,EFT-UU-004329,2026-05-15 18:35:08,119882.96,MZN,119882.96,D,00830107499893,Grupo Muianga Lda,175,680664409,00830103870989,Machava Energia e Recursos Naturais Lda,Transferência interna ref.4329,0,1
26,4354,EFT-UU-004354,2026-05-11 13:11:29,282574.24,MZN,282574.24,D,00830194737419,Muianga Telecomunicações Lda,161,193236414,00830136061160,Bila Importação e Exportação Lda,Transferência interna ref.4354,0,1
27,4371,EFT-UU-004371,2026-05-11 13:17:45,417065.52,MZN,417065.52,D,00830163512001,Grupo Nhacuamba S.A.,10,838353313,00830107467027,Moçambique Construção Civil Lda,Transferência interna ref.4371,0,1
28,4441,EFT-UU-004441,2026-05-11 12:27:11,509702.44,MZN,509702.44,D,00830188921602,Nhavene Educação Lda,173,668447103,00830104120627,Cuvele & Uamusse Lda,Transferência interna ref.4441,0,1
29,4858,EFT-UU-004858,2026-05-11 18:03:50,410922.83,MZN,410922.83,D,00830158128314,Moçambique Indústria Transformadora S.A.,36,711085601,00830180502337,Moçambique Tecnologia de Informação Lda,Transferência interna ref.4858,0,1
30,5326,EFT-UU-005326,2026-05-15 17:32:09,140857.21,MZN,140857.21,D,00830140712903,Grupo Uamusse S.A.,11,335920262,00830142942991,Machava Saúde e Farmácia Lda,Transferência interna ref.5326,0,1
31,5407,EFT-UU-005407,2026-05-15 12:50:18,128707.81,MZN,128707.81,D,00830162520380,Grupo Tembe Lda,107,437053227,00830107982497,Magaia & Sitoe SARL,Transferência interna ref.5407,0,1
32,5477,EFT-UU-005477,2026-05-15 15:42:27,684241.38,MZN,684241.38,D,00830191555691,Grupo Muianga Lda,171,896309911,00830165740754,Grupo Mondlane Lda,Transferência interna ref.5477,0,1
33,5547,EFT-UU-005547,2026-05-11 08:17:06,468912.85,MZN,468912.85,D,00830142942991,Machava Saúde e Farmácia Lda,121,601648440,00830127487165,Moçambique Construção Civil Lda,Transferência interna ref.5547,0,1
34,5560,EFT-UU-005560,2026-05-15 16:48:18,311462.48,MZN,311462.48,D,00830109669032,Machangana Energia e Recursos Naturais Lda,64,673646672,00830172102607,Moçambique Saúde e Farmácia Lda,Transferência interna ref.5560,0,1
35,5698,EFT-UU-005698,2026-05-15 07:53:05,124887.42,MZN,124887.42,D,00830174313364,Muchanga Consultoria e Assessoria Lda,144,714205566,00830160033666,Uamusse Hotelaria e Turismo Lda,Transferência interna ref.5698,0,1
36,6272,EFT-UU-006272,2026-05-12 08:21:53,433307.95,MZN,433307.95,D,00830177591009,Grupo Chemane Lda,6,403115662,00830125814412,Cuvele & Cuvele SARL,Transferência interna ref.6272,0,1
37,6303,EFT-UU-006303,2026-05-14 17:08:25,229037.43,MZN,229037.43,D,00830163512001,Grupo Nhacuamba S.A.,10,838353313,00830131027123,Cossa Consultoria e Assessoria Lda,Transferência interna ref.6303,0,1
38,6325,EFT-UU-006325,2026-05-15 10:01:26,519915.30,MZN,519915.30,D,00830141436760,Moçambique Transportes e Logística Lda,138,439205758,00830163512001,Grupo Nhacuamba S.A.,Transferência interna ref.6325,0,1
39,6333,EFT-UU-006333,2026-05-11 07:33:41,310012.72,MZN,310012.72,D,00830173209622,Guambe Importação e Exportação Lda,32,226298761,00830101057839,Moçambique Agricultura e Pecuária S.A.,Transferência interna ref.6333,0,1
40,6336,EFT-UU-006336,2026-05-15 10:13:09,249533.37,MZN,249533.37,D,00830187746424,Moçambique Serviços Financeiros S.A.,182,103815010,00830142171702,Moçambique Transportes e Logística S.A.,Transferência interna ref.6336,0,1
41,6404,EFT-UU-006404,2026-05-14 15:01:53,268174.53,MZN,268174.53,D,00830129586861,Machangana Indústria Transformadora Lda,185,737153642,00830121130596,Cumbe Energia e Recursos Naturais Lda,Transferência interna ref.6404,0,1
42,6490,EFT-UU-006490,2026-05-15 10:21:31,173236.98,MZN,173236.98,D,00830141436760,Moçambique Transportes e Logística Lda,138,439205758,00830176927735,Nhantumbo & Mondlane SARL,Transferência interna ref.6490,0,1
43,6561,EFT-UU-006561,2026-05-15 17:15:37,478961.05,MZN,478961.05,D,00830164628972,Mondlane Consultoria e Assessoria Lda,136,491152072,00830101175211,Grupo Uamusse Lda,Transferência interna ref.6561,0,1
44,6688,EFT-UU-006688,2026-05-13 14:39:56,356772.46,MZN,356772.46,D,00830118060910,Moçambique Transportes e Logística S.A.,111,657938168,00830132477500,Moçambique Comércio Geral S.A.,Transferência interna ref.6688,0,1
45,6806,EFT-UU-006806,2026-05-13 13:16:05,221829.53,MZN,221829.53,D,00830123637879,Sitoe & Mahumane Lda,158,705724933,00830171548008,Grupo Mabunda Lda,Transferência interna ref.6806,0,1
46,6843,EFT-UU-006843,2026-05-15 13:25:24,448906.43,MZN,448906.43,D,00830163935891,Grupo Zunguze S.A.,66,580936124,00830134674062,Muianga & Mabunda S.A.,Transferência interna ref.6843,0,1
47,7010,EFT-UU-007010,2026-05-12 12:45:57,551602.60,MZN,551602.60,D,00830153251117,Moçambique Saúde e Farmácia S.A.,70,474678197,00830185206634,Grupo Cuvele S.A.,Transferência interna ref.7010,0,1
48,7049,EFT-UU-007049,2026-05-11 17:49:38,561710.30,MZN,561710.30,D,00830139396593,Moçambique Saúde e Farmácia Lda,142,190768948,00830115219468,Moçambique Saúde e Farmácia Lda,Transferência interna ref.7049,0,1
49,7276,EFT-UU-007276,2026-05-15 15:45:55,444556.87,MZN,444556.87,D,00830199342278,Uamusse Energia e Recursos Naturais Lda,57,350613533,00830150580141,Machangana & Chemane Lda,Transferência interna ref.7276,0,1
50,7412,EFT-UU-007412,2026-05-15 15:51:20,692072.92,MZN,692072.92,D,00830111989974,Zunguze & Zunguze S.A.,58,608548589,00830153806726,Vilanculos Saúde e Farmácia Lda,Transferência interna ref.7412,0,1
51,7486,EFT-UU-007486,2026-05-15 08:57:40,237917.40,MZN,237917.40,D,00830164105055,Grupo Chaúque S.A.,181,996200491,00830175587967,Pateguana & Muchanga Lda,Transferência interna ref.7486,0,1
52,7830,EFT-UU-007830,2026-05-12 15:26:24,100308.51,MZN,100308.51,D,00830168927204,Nhateve Importação e Exportação Lda,45,438846548,00830132853853,Moçambique Indústria Transformadora Lda,Transferência interna ref.7830,0,1